name: Terraform apply infra change

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    name: dev
    needs: []
    runs-on: ubuntu-latest
    steps:
     - run: echo "running dev stage"

  sample:
    uses: ./.github/workflows/site-cd-workflow.yml
    with:
      working-directory: dev/sample
    secrets: inherit
    needs: [dev]

  5:
    uses: ./.github/workflows/site-cd-workflow.yml
    with:
      working-directory: dev/5
    secrets: inherit
    needs: [dev]

  qa:
    name: qa
    needs: [sample,5,dev]
    runs-on: ubuntu-latest
    steps:
     - run: echo "running qa stage"

  prod:
    name: prod
    needs: [qa]
    runs-on: ubuntu-latest
    steps:
     - run: echo "running prod stage"
